### ISSUE TITLE
have any roadmap for this project?

### ISSUE THREAD

**Issue by arden** [sagan-software/rust-eos#2]
have any roadmap for this project?

**Comment by liamcurry** [comment]
Hi @arden thanks for your interest in the project! There isn't a roadmap yet but I will be working on one soon.

Most of the features I want for v1.0 are now working, so now I need to clean up some code and work on documentation/branding. There should be an official announcement sometime next month. In the meantime if you're curious, the contracts in the `examples` folder should all be working and they are pretty close to what the v1.0 contracts will probably look like.

**Comment by liamcurry** [comment]
Hey @arden I added a roadmap section to the README here: https://github.com/sagan-software/rust-eos#roadmap

I'm going to close this issue now but please let me know if you have any questions about what I wrote. Thanks!
